### ISSUE TITLE
Why am I getting error CS0246: The type or namespace name could not be found?

### ISSUE THREAD

**Issue by FaisalAbusharar** [TechPenguineer/Hypermc#16]
**Describe the bug**
I'm talking about this repo, and this issue is only applying to me, when i save the sln and load the project again,i get this error: CS0246: The type or namespace name "System" could not be found

**To Reproduce**
Copy the repo HyperMC
open the csproj
then close it so you can save the sln
reload the project and open from sln
and maybe the same issue will happen, check program.cs

**Expected behavior**
this error on the using System; and etc should pop up: CS0246: The type or namespace name "System" could not be found

**Screenshots**
https://imgur.com/a/DFKhUuu

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by CobaltGoldCS** [comment]
Can you check your .csproj and make sure that ```Microsoft.CodeAnalysis.CSharp ``` Is not referenced twice? That seems to be a common issue

**Comment by FaisalAbusharar** [comment]
how can i check that? im sorry im just a bit new to C# and this error was out of the blue

**Comment by FaisalAbusharar** [comment]
and also i used the github repo, with no edits

**Comment by CobaltGoldCS** [comment]
It should be in the .csproj file. If it isn't then this problem has a different source.
Here is a [stackoverflow](https://stackoverflow.com/questions/33256896/the-type-or-namespace-name-system-could-not-be-found) for the issue

**Comment by FaisalAbusharar** [comment]
i already checked that stackoverflow post, and all of them, and i did not find anything about Microsoft.CodeAnalysis.CSharp, so yeah, maybe i missed it, so here is the file: https://www.mediafire.com/file/extpsbhb5iwncos/HyperMC.csproj/file
