### ISSUE TITLE
Possible misuse of init-only properties

### ISSUE THREAD

**Issue by AndrewToaster** [TechPenguineer/Hypermc#17]
From my review I think that the init-only properties should be replaced with read-only or read-write properties

Specifically:
## Mod.cs
```csharp
public string Name { get; init; }
```
As there is no constructor i think this property could become
```csharp
public string Name { get; set; }
```

## ModDownloadEventArgs.cs
```csharp
public Mod Mod { get; init; }
```
Due to the constructor and the 'EventArgs' suffix I think this could be a read-only property
```csharp
public Mod Mod { get; }
```

**Comment by TechPenguineer** [comment]
Thank you for the feedback! I will get a developer on it right away!

**Comment by FaisalAbusharar** [comment]
If you want, please contribute and i will put your updated code into a new branch for further testing
