### ISSUE TITLE
You shouldn't re-host mods

### ISSUE THREAD

**Issue by Krutonium** [TechPenguineer/Hypermc#2]
What you've done over on https://github.com/HyperMC-mods/mod-pack is simple and easy, right? But according to the licenses of those mods, you can't do that. Any one of them would be in the right to send you a DMCA takedown for that. I would recommend instead to figure out how to get the files from the original site. For example, for optifine you could use an embedded browser that wait's for an event for a file download ending in .jar. That way the mod developer stays happy (They get ad revenue) and you're not breaking the TOS (and the law) for those mods.

Heck, if you ask the mod developers, they might even have an API you could query to get the latest versions, with download links!

**Comment by TechPenguineer** [comment]
Thank you for the feedback. I was not aware of this. We will try to get an API key from a Minecraft mod listing site. Thank you for the information.

**Comment by VoidyCD** [comment]
if you saw, in the read me/download area, he says that is temporary, he is planning to use curseforge's API to fetch the mods, we might also add support to other mod loaders like fabric, but yeah, this isn't permanent.
