### ISSUE TITLE
TASK: Implement local storage for created mod packs

### ISSUE THREAD

**Issue by TechPenguineer** [TechPenguineer/Hypermc#23]
Hey... hi... what's up? So I cant figure out how but can someone make it so when you create a new mod pack it gets stored in a folder so when you close and relaunch the app it's still there? Please and thank you!

Cheers!
~ Head Developer

**Comment by mstew20** [comment]
Is this gonna be based on the mods that the user installs? Since it is for local use did you maybe want to go for like SQLLite to keep track of all this data?

**Comment by TechPenguineer** [comment]
I am not quite sure who this is gonna work. Im in charge of the API installer. You can talk to @AndrewToaster about that!

**Comment by AndrewToaster** [comment]
Of course, i was thinking more json files but SQLite could work too. Right now i'm figuring out how create minecraft instances (profiles)

**Comment by mstew20** [comment]
> Of course, i was thinking more json files but SQLite could work too. Right now i'm figuring out how create minecraft instances (profiles)

@AndrewToaster Let me know if you need any help with anything and see what we can put together.
