### ISSUE TITLE
Remove unnecessary copyright notices

### ISSUE THREAD

**Issue by AndrewToaster** [TechPenguineer/Hypermc#27]
I feel like throwing `(C) 2021 - Tech Penguin INC. All Rights Reserved` at every corner is very good. We can have a button in the setting view that displays stuff like that, but putting it in the Top bar feels cheap to me ngl.

My idea is to put legal information in a tab somewhere else then throwing it at the end user everywhere..

**Comment by TechPenguineer** [comment]
Hey! The reason I added copyright notices is because with our current license you can't remove them. So this insures if anyone tries to resell we get credit
