### ISSUE TITLE
Api Integration! HELP WANTED

### ISSUE THREAD

**Issue by TechPenguineer** [TechPenguineer/Hypermc#8]
Hi um, I'm the head developer here. I NEED HELP! BIG TIME! I can't figure out what API to use and how to get a list of Minecraft mods and their downloads. PLEASE HELP! Make a pull request if you know how!!

**Comment by strager** [comment]
> how to get a list of Minecraft mods and their downloads

Do you know of any website which hosts this information?

**Comment by CoconutMacaroon** [comment]
I'm not sure if they have an API, but [Curseforge](https://www.curseforge.com/minecraft/mc-mods) has tons of mods and downloads for them.

**Comment by strager** [comment]
> I'm not sure if they have an API, but [Curseforge](https://www.curseforge.com/minecraft/mc-mods) has tons of mods and downloads for them.

As of five months ago, Curseforge has no public API for querying mods, [according to u/ClayCorp](https://www.reddit.com/r/CurseForge/comments/lkk87h/curseforge_api/gnkl1oe/).

**Comment by mstew20** [comment]
From what I have found strager is correct there is no public API and the API that Curseforge provides does have much: https://support.curseforge.com/en/support/solutions/articles/9000197321-curseforge-api 

However I did find that there is a nuget package that someone has made ForgedCurse which looks like may do the job. The urls they call are also provided if you just wanted to make your own API calls. https://www.nuget.org/packages/ForgedCurse/

I have put together an example of using the endpoint that is used in the nuget package with my own client if you would like to see the result of it. It is in WPF currently though as thats what I primarily use and readily have a test environment for but could easily transfer over to WinForms.

**Comment by Grrenix** [comment]
I have also done some searching around and found an Apiary API that seems like it could be useful should ForgedCurse not workout https://curseforgeapi.docs.apiary.io/

**Comment by mstew20** [comment]
> I have also done some searching around and found an Apiary API that seems like it could be useful should ForgedCurse not workout https://curseforgeapi.docs.apiary.io/

Looks like you actually found the api that ForgedCurse uses nice. Uses the endpoints I was able to pull out of it.

**Comment by mstew20** [comment]
I would be happy to write out this feature using whatever API is decided upon even if that means building one from the provided docs. Please let me know I will start getting some stuff put together.

**Comment by TechPenguineer** [comment]
> I would be happy to write out this feature using whatever API is decided upon even if that means building one from the provided docs. Please let me know I will start getting some stuff put together.

I see. Thank you so much! As of right now, we are struggling to decide what API to use but we did find a curse forge API wrapper. I'm wondering if you can use that? The wrapper was made by @AndrewToaster who I trust right now but if there is a way to implement that into the project go right ahead.
